version: "3.4"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # payments:
  #   image: rivancic/json-server-faker:latest
  #   volumes:
  #     - ./examples/webshop/config/:/
  #     - ./examples/webshop/config/file.js:/data/file.js
  #   ports:
  #     - "4000:80"

  api:
    build:
      context: .
      target: go-build
    environment:
      GO_ENV: "development"
      GJ_DATABASE_HOST: db
      GJ_DATABASE_USER: postgres
      GJ_DATABASE_PASSWORD: postgres
      CGO_ENABLED: 0
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/home/nonroot
      - ./examples/webshop/config:/home/nonroot/config
    working_dir: /home/nonroot
    command: wtc
    depends_on:
      - db
      # - rails_app
    # - redis
